version: '3'
services:
  mongodb32:
    networks:
      - mongo
    image: mongo:3.2.10
    command: mongod --port 27018
    ports:
      - '27018:27018'
  mongodb34:
    networks:
      - mongo
    image: mongo:3.4.24
    command: mongod --port 27019
    ports:
      - '27019:27019'
  mongodb36:
    networks:
      - mongo
    image: mongo:3.6.18
    command: mongod --port 27020
    ports:
      - '27020:27020'

networks:
  mongo:
